name: "Self-Hosted"
include:
  # Core Services
  - ./services/authentik.yml
  - ./services/caddy/caddy.yml
  - ./services/portainer.yml

  # Storage
  - ./services/nextcloud.yml
  - ./services/gitlab.yml
  - ./services/vaultwarden.yml  
  - ./services/immich.yml

  # AI
  - ./services/openwebui.yml
  - ./services/stable-diffusion.yml
  - ./services/edge-tts.yml

  # Other
  - ./services/vuetorrent.yml
  - ./services/umami.yml
  - ./services/adguard.yml

# ---- Disabled ----
#  - ./services/bitwarden.yml
#  - ./services/dozzle.yml
#  - ./services/radicale.yml
#  - ./services/collabora-code.yml

services:
  unhealthy_container_restarter:
    container_name: watcher
    image: docker:cli
    network_mode: none
    cap_drop:
      - ALL
    volumes: [ "/var/run/docker.sock:/var/run/docker.sock" ]
    command: [ "/bin/sh", "-c", "while true; do sleep 60; docker ps -q -f health=unhealthy | xargs --no-run-if-empty docker restart; done" ]
    restart: always

networks:
  caddy_network:
    ipam:
      driver: default
      config:
        - subnet: 172.11.0.0/16
  ai_network:
