services:
  collabora-code:
    container_name: collabora-code
    image: collabora/code
    ports:
      - "9980:9980"
    volumes:
      - ${DATA_DIR}collabora-code/config:/etc/coolwsd
    restart: always
    networks:
      - caddy_network
