services:
  collabora-code:
    name: collabora-code
    image: collabora/code
    volumes:
      - ${DATA_DIR}collabora-code/config:/etc/coolwsd
    restart: always
    networks:
      - caddy_network
