services:
  stable-diffusion:
    build:
      context: ../images/stable-diffusion
      dockerfile: stable-diffusion.dockerfile
    volumes:
      - ${DATA_DIR}picai:/app/models
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    container_name: stable-diffusion
    networks:
      - ai_network
      - caddy_network
