services:
  vuetorrent:
    image: linuxserver/qbittorrent:latest
    container_name: vuetorrent
    restart: always
    environment:
      PUID: 1000
      PGID: 1000
      UMASK_SET: 022
      WEBUI_PORT: 80
      DOCKER_MODS: ghcr.io/vuetorrent/vuetorrent-lsio-mod:latest
    volumes:
      - ${DATA_DIR}/torrent/config:/config
      - ${DATA_DIR}/torrent/downloads:/downloads
    networks:
      caddy_network:
